source("scripts/BasesDiarias.R")
source("scripts/Tablaactivos.R", encoding="utf-8")
source("scripts/espiralocurrido.R", encoding="utf-8")
source("scripts/Mapas.R", encoding="utf-8")
# source("scripts/diarioedad.R", encoding="utf-8")
source("scripts/Gráficos semanales.R", encoding="utf-8")
source("scripts/Resumenmunicipios.R", encoding="utf-8")
source("scripts/Incidencia regional semanalCDC.R", encoding="utf-8")
source("scripts/waffles.R", encoding="utf-8")
rmarkdown::render("docs/index.Rmd")
